# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 12d4b86e852e1a5557af429dd349694ea2109aa76d7276d7c71002b25dab5c916f3312471363a621248b6572773e4ccf473baeb8000c3c969f0240b15b6fdeaa

test:
  secret_key_base: f9e5df274dd871d4b1f1a9d6e5b4974ab732477b45f11f993c4cac9aa6202eb088df007700e80dbf23b9a75252898b861d65b81d1d7e720c0c8f9217035bfcf1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
